- hosts: all
  gather_facts: no
  tasks:
  - name: drop access logs
    copy:
      src: files/3-output-50-sumologic
      dest: /usr/lib/buddy/logstash/app/conf.d/
      owner: root
      group: root
      mode: 0644
  - command: systemctl restart logstash-worker
