- hosts: all
  gather_facts: no
  tasks:
  - name: example copying file with owner and permissions
    copy:
      src: files/2-filter-99-sleep
      dest: /usr/lib/buddy/logstash/app/conf.d/
      owner: root
      group: root
      mode: 0644
  - command: systemctl restart logstash-worker
